In [1]:
# numpy is a wrapper for numerical librarys
# Works with "ndarray's"

In [3]:
"""Creating NumPy arrays"""
import numpy as np

def test_run():
    # List to 1D array
    print np.array([2,3,4])
    
if __name__ == "__main__":
    test_run()

[2 3 4]


In [4]:
"""Creating NumPy arrays"""
import numpy as np

def test_run():
    # List of tuples to 2D array
    print np.array([(2,3,4), (5,6,7)])
    
if __name__ == "__main__":
    test_run()

[[2 3 4]
 [5 6 7]]


In [5]:
"""Creating NumPy arrays"""
import numpy as np

def test_run():
    # Empty array
    print np.empty(5)
    print np.empty((5,4))
    
    
if __name__ == "__main__":
    test_run()

[  4.67999260e-310   6.92789875e-310   6.92789875e-310   6.51913678e+091
   2.37151510e-322]
[[  6.92790753e-310   4.67999259e-310   0.00000000e+000   1.27319747e-313]
 [  1.27319747e-313   1.27319747e-313   1.27319747e-313   1.27319747e-313]
 [  0.00000000e+000   1.90979621e-313   1.90979621e-313   1.90979621e-313]
 [  1.90979621e-313   1.90979621e-313   0.00000000e+000   5.92878775e-323]
 [  3.18299369e-313   0.00000000e+000   4.03179200e-313   9.88131292e-323]]


In [6]:
"""Creating NumPy arrays"""
import numpy as np

def test_run():
    # array of ones *default is float
    print np.ones((5,4))
     
    
if __name__ == "__main__":
    test_run()

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [7]:
"""Creating NumPy arrays"""
import numpy as np

def test_run():
    # 'dtype' is the paramater and 
    print np.ones((5,4), dtype=np.int_)
     
    
if __name__ == "__main__":
    test_run()

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [8]:
"""Creating random numbers"""
import numpy as np

def test_run():
    print np.random.rand(5,4)
     
    
if __name__ == "__main__":
    test_run()

[[ 0.43515911  0.10388048  0.77168119  0.44990323]
 [ 0.92154151  0.04857488  0.08351129  0.75019514]
 [ 0.88499981  0.15679885  0.36364522  0.02787718]
 [ 0.52365017  0.38372962  0.65359745  0.84249872]
 [ 0.60631174  0.5974379   0.65697972  0.69778499]]


In [9]:
"""Creating random numbers"""
import numpy as np

def test_run():
    print np.random.normal(size=(2,3))  # standard normal mean=0
     
    
if __name__ == "__main__":
    test_run()

[[-0.9079735   0.50628033 -0.6998063 ]
 [-0.57625447  1.18400394  1.51716474]]


In [10]:
"""Creating random numbers"""
import numpy as np

def test_run():
    print np.random.normal(50, 10, size=(2,3))  #  mean=50 and s.d to 10
     
    
if __name__ == "__main__":
    test_run()

[[ 51.95231879  59.46547814  49.41607046]
 [ 45.10994091  51.35308986  43.33655258]]


In [24]:
"""Array attributes"""
import numpy as np

def test_run():
    a = np.random.random((5,4))
    print a.shape[0] # rows
    print a.shape[1] # columsn
    print len(a.shape) # array dimention
    print a.size #number of attributes
    print a.dtype
    
if __name__ == "__main__":
    test_run()

5
4
2
20
float64


In [11]:
"""Ops on attributes"""
import numpy as np

def test_run():
    np.random.seed(693)
    a = np.random.randint(0, 10, size=(5,4))
    print "Array:\n", a
    
    #sum all elemts
    print "Sum of all elements:\n", a.sum()
    
    #sum each column
    print "Sum of each column:\n", a.sum(axis=0)
    
    
if __name__ == "__main__":
    test_run()

Array:
[[2 0 5 1]
 [1 3 4 4]
 [9 2 9 1]
 [9 3 7 5]
 [4 7 0 3]]
Sum of all elements:
79
Sum of each column:
[25 15 25 14]


In [29]:
"""Ops on attributes"""
import numpy as np

def test_run():
    np.random.seed(693)
    a = np.random.randint(0, 10, size=(5,4))
    print "Array:\n", a
    
    #stastics: min, max, mean(across rows, cols, and overall)
    print "Min of each col:\n", a.min(axis=0)
    print "Max of each row:\n", a.max(axis=1)
    print "Mean of all elements:\n", a.mean()
    
    
    
if __name__ == "__main__":
    test_run()

Array:
[[2 0 5 1]
 [1 3 4 4]
 [9 2 9 1]
 [9 3 7 5]
 [4 7 0 3]]
Min of each col:
[1 0 0 1]
Max of each row:
[5 4 9 9 7]
Mean of all elements:
3.95


In [31]:
"""Locate max value"""
import numpy as np

def get_max_index(a):
    """Return the index of the maximum value in given 1D array"""
    return a.argmax()
    

def test_run():
    a = np.array([9,6,2,3,12,14,7,10], dtype=np.int32)
    print "Array:\n", a
    
    #find max and index in the array
    print "Max value:", a.max()
    print "Index of max.:", get_max_index(a)
    
    
    
if __name__ == "__main__":
    test_run()

 Array:
[ 9  6  2  3 12 14  7 10]
Max value: 14
Index of max.: 5


In [12]:
"""using time fun"""

import time

def test_run():
    t1 = time.time()
    print "ML4T"
    t2 = time.time()
    print "The time taken by print statement is ",t2 - t1," seconds"


if __name__ == "__main__":
    test_run()

ML4T
The time taken by print statement is  0.000231027603149  seconds


In [37]:
"""accessing array elemts"""

def test_run():
    a = np.random.rand(5,4)
    print "Array: \n", a
    
    # accessing element at position (3,2)
    element = a[3,2]
     
    #elements in defined range
    print a[0, 1:3]  #column slicing
    
    print a[:, 0:3:2]
    
    
    
if __name__ == "__main__":
    test_run()

Array: 
[[ 0.29624151  0.52007049  0.19683409  0.0186893 ]
 [ 0.86612927  0.39325211  0.0971765   0.91781428]
 [ 0.45766729  0.89664398  0.32742972  0.80625555]
 [ 0.47246616  0.2393383   0.74850448  0.2744893 ]
 [ 0.38065952  0.2396454   0.49605158  0.47252039]]
[ 0.52007049  0.19683409]
[[ 0.29624151  0.19683409]
 [ 0.86612927  0.0971765 ]
 [ 0.45766729  0.32742972]
 [ 0.47246616  0.74850448]
 [ 0.38065952  0.49605158]]


In [38]:
"""accessing array elemts"""

def test_run():
    a = np.random.rand(5,4)
    print "Array: \n", a
    
    # accessing element at position (3,2)
    a[0,0] = 1
    print "\n Modified (replaced one element):\n",a
      
    
    
    
if __name__ == "__main__":
    test_run()

Array: 
[[ 0.55954643  0.69960098  0.77345467  0.63399027]
 [ 0.66652527  0.1283678   0.5497237   0.87219761]
 [ 0.21252231  0.96637449  0.39893195  0.66724993]
 [ 0.76185981  0.50517548  0.31735514  0.05505354]
 [ 0.05316876  0.63555341  0.5410938   0.85408341]]

 Modified (replaced one element):
[[ 1.          0.69960098  0.77345467  0.63399027]
 [ 0.66652527  0.1283678   0.5497237   0.87219761]
 [ 0.21252231  0.96637449  0.39893195  0.66724993]
 [ 0.76185981  0.50517548  0.31735514  0.05505354]
 [ 0.05316876  0.63555341  0.5410938   0.85408341]]


In [39]:
"""accessing array elemts"""

def test_run():
    a = np.random.rand(5,4)
    print "Array: \n", a
    
    # accessing element at position (3,2)
    a[:,3] = [1,2,3,4,5]
    print "\n Modified (replaced one element):\n",a
      
    
    
    
if __name__ == "__main__":
    test_run()

Array: 
[[ 0.71819427  0.23147459  0.50620594  0.59499413]
 [ 0.34370863  0.42590808  0.236121    0.88377603]
 [ 0.09617875  0.53969969  0.99614293  0.80829174]
 [ 0.23905794  0.60767761  0.96859421  0.41604617]
 [ 0.83385194  0.07423688  0.48683308  0.2981861 ]]

 Modified (replaced one element):
[[ 0.71819427  0.23147459  0.50620594  1.        ]
 [ 0.34370863  0.42590808  0.236121    2.        ]
 [ 0.09617875  0.53969969  0.99614293  3.        ]
 [ 0.23905794  0.60767761  0.96859421  4.        ]
 [ 0.83385194  0.07423688  0.48683308  5.        ]]


In [43]:
"""accessing array elemts"""

def test_run():
    a = np.random.rand(5)
    print a
    # accessing element at 
    indices = np.array([1,2,3])
    print a[indices]
    
if __name__ == "__main__":
    test_run()

[ 0.02539469  0.94615825  0.90069396  0.79418693  0.14458579]
[ 0.94615825  0.90069396  0.79418693]


In [46]:
"""accessing array elemts"""

def test_run():
    a = np.array([(20,25,10,23,26,23,10,5,0),(0,2,50,20,0,1,28,5,0)])
    print a
    
    mean = a.mean()
    print mean
    
    #masking
    print a[a<mean]
    
if __name__ == "__main__":
    test_run()

[[20 25 10 23 26 23 10  5  0]
 [ 0  2 50 20  0  1 28  5  0]]
13.7777777778
[10 10  5  0  0  2  0  1  5  0]


In [47]:
"""accessing array elemts"""

def test_run():
    a = np.array([(1,2,3,4,5),(10,20,30,40,50)])
    print "Original array a:\n", a
    
    # multiply a by 2
    print "\nMultiply a by 2:\n", 2 * a
    
if __name__ == "__main__":
    test_run()

Original array a:
[[ 1  2  3  4  5]
 [10 20 30 40 50]]

Multiply a by 2:
[[  2   4   6   8  10]
 [ 20  40  60  80 100]]
